---
- name: collection_test
  hosts: localhost

  tasks:
    - name: Run date command
      command: date
      register: curdate

    - name: Debug curdate
      debug:
        var: curdate

    # Gather info for selected units with extra properties.
    - name: Gather info for selected unit(s)
      systemd_info:
        unitname:
          - k3s.service
        extra_properties:
          - Description
      register: systemd_results

    - name: Debug systemd_results
      debug:
        var: systemd_results
